---
no-trailing-punctuation: false
no-inline-html: false
first-line-heading: false
link-fragments: false

# MD013 - Line length
MD013:
  code_block_line_length: 125
  code_blocks: true
  heading_line_length: 80
  headings: true
  line_length: 125
  stern: true
  strict: false
  tables: false

