name: 🐞 Bug report
description: Create a bug report to help us improve
title: "Bug: <title>"
labels: ["bug"]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: Describe below what the problem is
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behaviour
    description: Describe below what you expected to happen
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Version**: 2.5.0
        - **Platform**: Web App / Desktop App
        - **OS**: MacOS / Windows / Linux
        - **Browser**: chrome, firefox, safari
    value: |
        - Version:
        - Platform:
        - OS:
        - Browser:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: List below the steps to reproduce the behaviour
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add below any other context or screenshots about this bug

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

