name: Feature request
description: Suggest an idea for this project
title: "Feature: <title>"
labels: ["enhancement"]
body:
- type: textarea
  attributes:
    label: Describe what problem your feature request solves
    description: Describe below what the problem is
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you would like
    description: Describe below what you want to happen
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add below any other context or screenshots about the feature request

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../code_of_conduct.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
      label: Contributing guidelines
      description: and have read the [contributing guidelines](../contributing.md).
      options:
        - label: I have read the contributing guidelines
          required: true
