import assumptions from '../assumptions';
import controls from './controls';
import personas from './personas';
import risks from './risks';
import { v4 as uuidv4 } from 'uuid';

// Threat Dragon has no concept of threat persona, but TM-BOM threats require one
const defaultThreatPersona = {
    symbolic_name: uuidv4(),
    title: 'Default threat persona',
    description: 'Threat persona generated by export from Threat Dragon',
    is_person: false,
    skill_level: 'expert_engineer',
    access_level: 'anonymous',
    malicious_intent: true,
    applicability_to_org: 'high'
};
const defaultLikelihood = 'certain';
const defaultRiskLevelBand = 'high';

const convertImpact = {Low: 'minor', Medium: 'moderate', High: 'major', Critical: 'severe'};

const convert = (model) => { 
    let vulns = {
        controls: [],
        risks: [],
        threats: [],
        threat_personas: [defaultThreatPersona]
    };

    // there may be no diagrams, or no cells within a diagram, or no threats for a cell
    model.detail.diagrams?.forEach((diagram) => {
        diagram.cells?.forEach((cell) => {
            cell.data.threats?.forEach((threat) => {
                let riskId = uuidv4();
                let riskScore = parseInt(threat.score) || 0;
                vulns.risks.push({
                    symbolic_name: riskId,
                    title: threat.title,
                    description: 'Risk: ' + threat.title,
                    threats: [threat.id],
                    likelihood: defaultLikelihood,
                    impact: convertImpact[threat.severity],
                    impact_description: 'The impact of the risk materializing is ' + convertImpact[threat.severity],
                    score: Math.round(riskScore > 10 ? riskScore / 4 : riskScore * 2.5),
                    level: defaultRiskLevelBand
                });
            });
        });
    });

    return vulns;
};

const merge = (model) => {
    let tdThreats = new Array();

    model.threats?.forEach((threat) => {
        let description = threat.description;

        // threat.event is a value required by the schema
        description += '\nOn event : ' + threat.event;

        if (threat.attack_mechanisms) {
            let mechanisms = threat.attack_mechanisms;
            description += '\nUsing attack mechanism : ';
            mechanisms.forEach((mechanism) => {
                description += '\n' + ' CAPEC-' + mechanism.capec_id + ' : ' + mechanism.capec_title;
            });
        }

        if (threat.weaknesses) {
            let weaknesses = threat.weaknesses;
            description += '\nExploiting weakness : ';
            weaknesses.forEach((weakness) => {
                description += '\n' + ' CWE-' + weakness.cwe_id + ' : ' + weakness.cwe_title;
            });
        }

        // sources is a required key
        description += '\nExample attack vectors from :';
        for (let source of threat.sources) {
            description += '\n- ' + source.replaceAll('_', ' ');
        }

        // threat.threat_persona is a value required by the schema
        description += '\n' + personas.merge(model, threat.threat_persona);

        tdThreats.push({
            status: 'Open',
            severity: 'TBD',
            description: description,
            title: threat.title,
            type: 'Generic',
            mitigation: '',
            modelType: 'Generic',
            id: threat.symbolic_name,
            new: false,
            components_affected: threat.components_affected
        });
    });

    tdThreats = controls.merge(model, tdThreats);
    tdThreats = assumptions.merge(model, tdThreats);
    tdThreats = risks.merge(model, tdThreats);

    return tdThreats;
};

export default {
    convert,
    merge
};
