export const ERROR_CODES = Object.freeze({
    CONFIG_INVALID_ENTRY: 'CONFIG_INVALID_ENTRY',
    CONFIG_LOCALE_MISSING: 'CONFIG_LOCALE_MISSING',
    CONFIG_LOCALE_PARSE: 'CONFIG_LOCALE_PARSE',
    CONFIG_LOCALE_NOT_ARRAY: 'CONFIG_LOCALE_NOT_ARRAY',
    CONFIG_LOCALE_TYPE: 'CONFIG_LOCALE_TYPE',
    CONFIG_LOCALE_FORMAT: 'CONFIG_LOCALE_FORMAT',
    CONFIG_LOCALE_BCP47: 'CONFIG_LOCALE_BCP47'
});
