name: owasp-threat-dragon
version: 1.5.0
summary: OWASP Threat Dragon
description: |
  OWASP Threat Dragon is a free, open-source, cross-platform threat modelling application including system diagramming and a threat rule engine to auto-generate threats/mitigations.  The roadmap for the project is a simple UX, a powerful rule engine and integration with other development lifecycle tools.
icon: public/content/icons/png/256x256.png
license: Apache-2.0
base: core18
type: app
grade: stable
confinement: strict


apps:
  threatdragon:
    command: bin/threat-dragon
    extensions: [gnome-3-34]
    plugs:
    - browser-support
    - network
    - network-bind
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  threatdragon:
    plugin: nil
    source: https://github.com/owasp/threat-dragon.git
    override-build: |
        npm install electron electron-packager
        npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./threat* $SNAPCRAFT_PART_INSTALL/threatdragon
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4
