name: owasp-threat-dragon
grade: stable
version: 1.5.0
summary: OWASP Threat Dragon
description: |
  OWASP Threat Dragon is a free, open-source, cross-platform threat modelling application including system diagramming and a threat rule engine to auto-generate threats/mitigations.  The roadmap for the project is a simple UX, a powerful rule engine and integration with other development lifecycle tools.
confinement: strict
license: Apache-2.0
image: public/content/icons/png/256x256.png
