export default {
    strideHeader:  'threats.model.stride.header',
    spoofing: 'threats.model.stride.spoofing',
    tampering: 'threats.model.stride.tampering',
    repudiation: 'threats.model.stride.repudiation',
    informationDisclosure: 'threats.model.stride.informationDisclosure',
    denialOfService: 'threats.model.stride.denialOfService',
    elevationOfPrivilege: 'threats.model.stride.elevationOfPrivilege',
    ciaHeader:  'threats.model.cia.header',
    confidentiality: 'threats.model.cia.confidentiality',
    integrity: 'threats.model.cia.integrity',
    availability: 'threats.model.cia.availability',
    linddunHeader:  'threats.model.linddun.header',
    linkability: 'threats.model.linddun.linkability',
    identifiability: 'threats.model.linddun.identifiability',
    nonRepudiation: 'threats.model.linddun.nonRepudiation',
    detectability: 'threats.model.linddun.detectability',
    disclosureOfInformation: 'threats.model.linddun.disclosureOfInformation',
    unawareness: 'threats.model.linddun.unawareness',
    nonCompliance: 'threats.model.linddun.nonCompliance'
};
