'use strict';
window.jQuery = require('jquery');
require('bootstrap');
require('./services/joint.shapes.tm');
require('./templates');
require('./config');
require('./common');
require('./services');
require('./diagrams');
require('./layout');
require('./threatmodels');