export const DATASOURCE_PROVIDER_SELECTED = 'DATASOURCE_PROVIDER_SELECTED';
export const DATASOURCE_PROVIDER_CLEAR = 'DATASOURCE_PROVIDER_CLEAR';
export const DATASOURCE_REPOSITORY_SELECTED = 'DATASOURCE_REPOSITORY_SELECTED';
export const DATASOURCE_REPOSITORY_CLEAR = 'DATASOURCE_REPOSITORY_CLEAR';
export const DATASOURCE_BRANCH_SELECTED = 'DATASOURCE_BRANCH_SELECTED';
