export const THREATMODEL_CLEAR = 'THREATMODEL_CLEAR';
export const THREATMODEL_DIAGRAM_UPDATED = 'THREATMODEL_DIAGRAM_UPDATED';
export const THREATMODEL_FETCH = 'THREATMODEL_FETCH';
export const THREATMODEL_FETCH_ALL = 'THREATMODEL_FETCH_ALL';
export const THREATMODEL_SELECTED = 'THREATMODEL_SELECTED';
export const THREATMODEL_DIAGRAM_SELECTED = 'THREATMODEL_DIAGRAM_SELECTED';
export const THREATMODEL_CREATE = 'THREATMODEL_CREATE';
export const THREATMODEL_CONTRIBUTORS_UPDATED = 'THREATMODEL_CONTRIBUTORS_UPDATED';
export const THREATMODEL_RESTORE = 'THREATMODEL_RESTORE';

export default {
    clear: THREATMODEL_CLEAR,
    create: THREATMODEL_CREATE, 
    diagramUpdated: THREATMODEL_DIAGRAM_UPDATED,
    fetch: THREATMODEL_FETCH,
    fetchAll: THREATMODEL_FETCH_ALL,
    selected: THREATMODEL_SELECTED,
    restore: THREATMODEL_RESTORE
};
