export const THREATMODEL_CLEAR = 'THREATMODEL_CLEAR';
export const THREATMODEL_FETCH = 'THREATMODEL_FETCH';
export const THREATMODEL_FETCH_ALL = 'THREATMODEL_FETCH_ALL';
export const THREATMODEL_SELECTED = 'THREATMODEL_SELECTED';

export default {
    clear: THREATMODEL_CLEAR,
    fetch: THREATMODEL_FETCH,
    fetchAll: THREATMODEL_FETCH_ALL,
    selected: THREATMODEL_SELECTED
};
