name: BrowserStack End to End Tests
concurrency: browserstack_e2e
on:
  # Run daily at 8:40
  schedule:
    - cron: '40 8 * * *'
  workflow_dispatch:

permissions:
  contents: read

# for security reasons the github actions are pinned to specific SHAs
jobs:
  browserstack_e2e:
    name: Browserstack e2e
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: td.vue
    if: github.repository == 'OWASP/threat-dragon'

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use node LTS 24.15
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24.15'

      - name: Cache NPM dir
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install packages
        run: |
          npm clean-install

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@93aebce225b754566349151c0676b26b005e591b # v1.0.4
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: Run e2e tests
        run: npm run test:e2e-nightly
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
