name: Build/Release Desktop
on:
  push:
    branches: [ feature/112-automate-release-process ] # TODO: Change to main, maybe not on push but on tags?
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: td.desktop
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Cache NPM dir
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache-server-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-server-

    - run: npm ci
    - run: npm run build
    - run: npm run pretest
    - run: |
        export DISPLAY=':99.0'
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        npm run test
  
  release:
    runs-on: ${{ matrix.config.os }}
    needs: [test]
    strategy:
      matrix:
        config:
          - { os: macos-latest, os_short: osx }
          - { os: ubuntu-latest, os_short: lin }
          - { os: windows-latest, os_short: win }
    defaults:
      run:
        working-directory: td.desktop

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npm ci
      - run: npm run build

      # TODO
      # - name: Prepare for app notarization
      #   if: startsWith(matrix.os, 'macos')
      #   # Import Apple API key for app notarization on macOS
      #   run: |
      #     mkdir -p ~/private_keys/
      #     echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8

      # TODO: For OSx and Windows
      # Win and OSX will just publish to the GH Release Draft (and create it if needed based on version)
      # Snap publishing fails using this plugin, so special care is needed for linux
      - name: Build/release Electron app
        if: ${{ !startsWith(matrix.config.os, 'ubuntu') }}
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          # release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          # TODO: Just testing
          release: true

          # TODO:
          # mac_certs: ${{ secrets.mac_certs }}
          # mac_certs_password: ${{ secrets.mac_certs_password }}
          # windows_certs: ${{ secrets.windows_certs }}
          # windows_certs_password: ${{ secrets.windows_certs_password }}

          package_root: td.desktop
        # TODO
        # env:
        #   # macOS notarization API key
        #   API_KEY_ID: ${{ secrets.api_key_id }}
        #   API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}

      

      # Win and OSX will just publish to the GH Release Draft (and create it if needed based on version)
      # TODO: Delete after testing
      # - shell: bash
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #   run: npm run build:${{ matrix.config.os_short }} -- --publish always
      #   if: ${{ !startsWith(matrix.config.os, 'ubuntu') }}

      # Build all linux images EXCEPT for the snap, with publish always
      # Snaps will not publish, even with snapcraft installed
      - shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run electron-builder -- --linux AppImage deb rpm --publish always
        if: startsWith(matrix.config.os, 'ubuntu')

      # Build the snap, but do not publish
      - shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run electron-builder -- --linux snap
        if: startsWith(matrix.config.os, 'ubuntu')

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        # Only install Snapcraft on Ubuntu
        with:
          # Log in to Snap Store
          snapcraft_token: ${{ secrets.snapcraft_token }}
        if: startsWith(matrix.config.os, 'ubuntu')

      # TODO: Uncomment when ready to start deploying again
      # - shell: bash
      #   run: snapcraft upload --release=stable installers/threat-dragon-desktop*.snap
      #   if: startsWith(matrix.config.os, 'ubuntu')
