name: Build/Release Desktop
on:
  push:
  #   branches: [ feature/112-automate-release-process ] # TODO: Change to main, maybe not on push but on tags?
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: td.desktop
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Cache NPM dir
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache-server-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-server-

    - run: npm ci
    - run: npm run build
    - run: npm run pretest
    - run: |
        export DISPLAY=':99.0'
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        npm run test
  
  release:
    runs-on: ${{ matrix.config.os }}
    needs: [test]
    strategy:
      matrix:
        config:
          - { os: macos-latest, os_short: osx }
          - { os: ubuntu-latest, os_short: lin }
          - { os: windows-latest, os_short: win }
    defaults:
      run:
        working-directory: td.desktop

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npm ci
      - run: npm run build

      # Win and OSX will just publish to the GH Release Draft (and create it if needed based on version)
      - shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build:${{ matrix.config.os_short }} -- --publish always
        if: ${{ !startsWith(matrix.config.os, 'ubuntu') }}

      # Build all linux images EXCEPT for the snap, with publish always
      # Snaps will not publish, even with snapcraft installed
      - shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run electron-builder -- --linux AppImage deb rpm --publish always
        if: startsWith(matrix.config.os, 'ubuntu')

      # Build the snap, but do not publish
      - shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run electron-builder -- --linux snap
        if: startsWith(matrix.config.os, 'ubuntu')

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        # Only install Snapcraft on Ubuntu
        with:
          # Log in to Snap Store
          snapcraft_token: ${{ secrets.snapcraft_token }}
        if: startsWith(matrix.config.os, 'ubuntu')

      - shell: bash
        run: snapcraft upload --release=stable installers/threat-dragon-desktop*.snap
        if: startsWith(matrix.config.os, 'ubuntu')
