name: Release to Snap

on:
  workflow_dispatch:

permissions:
  contents: read

# for security reasons the github actions are pinned to specific SHAs
jobs:
  desktop_linux_snap:
    name: Linux snap
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    defaults:
      run:
        working-directory: td.vue

    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use node LTS 24.14
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24.14'

      - name: Cache NPM dir
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install clean packages
        run: |
          sudo snap install snapcraft --classic
          npm clean-install

      # Build the snap, but do not use inbuilt publish
      # Snaps do not publish, even with snapcraft installed, so use Snap Store
      - name: Build Linux snap
        shell: bash
        run: npm run build:desktop -- --linux snap

      - name: Upload to Snap Store
        shell: bash
        run: |
          ls -l dist-desktop/threat-dragon*.snap
          snapcraft upload --release=stable dist-desktop/threat-dragon*.snap

      - name: Print logs on error
        if: ${{ failure() }}
        run: find . -name "*.log" -exec cat '{}' \; -print

      - name: Save SBOM artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: sboms-desktop-linux-snap-site
          path: './td.vue/dist-desktop/bundled/.sbom/*'
          include-hidden-files: true
          if-no-files-found: error
