name: Windows release

on:
  workflow_dispatch:

permissions:
  contents: write

# for security reasons the github actions are pinned to specific SHAs
jobs:

  desktop_windows:
    name: Windows installer
    runs-on: windows-latest
    defaults:
      run:
        working-directory: td.vue

    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use node LTS 24.15
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24.15'

      - name: Cache NPM dir
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install clean packages
        run: npm clean-install

      - name: Build Windows executable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder
          # code signing using Extended Verification (EV) open source certificate
          CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_OSS_CERT_PASSWORD}}
          CSC_LINK:  ${{ secrets.WINDOWS_OSS_CERT }}
        run: npm run build:desktop -- --windows --publish always

      - name: Save SBOM artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sboms-desktop-windows-site
          path: './td.vue/dist-desktop/bundled/.sbom/*'
          include-hidden-files: true
          if-no-files-found: error
